// <auto-generated />
using CoreDepartman.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreDepartman.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211016053203_Admin")]
    partial class Admin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreDepartman.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Kullanici")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sifre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("CoreDepartman.Models.Birim", b =>
                {
                    b.Property<int>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BirimAd")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BirimID");

                    b.ToTable("Birims");
                });

            modelBuilder.Entity("CoreDepartman.Models.Personel", b =>
                {
                    b.Property<int>("PerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PerId");

                    b.HasIndex("BirimId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("CoreDepartman.Models.Personel", b =>
                {
                    b.HasOne("CoreDepartman.Models.Birim", "Birim")
                        .WithMany("Personels")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
